<?php

namespace Tests\Domain\Shared\Entity;

use App\Domain\Shared\Entity\Sesion;
use App\Domain\Shared\ValueObject\Fecha;
use App\Domain\Shared\ValueObject\Hora;
use App\Domain\Shared\ValueObject\Id;
use Carbon\Carbon;
use PHPUnit\Framework\TestCase;

class SesionTest extends TestCase
{
  protected function setUp(): void
  {
    parent::setUp(); // TODO: Change the autogenerated stub

    Carbon::setTestNow(Carbon::parse("2020-01-01 14:15"));
  }

  public function testAvailableSesion_Case1() {
    $sesion = Sesion::fromPrimitives(
      Id::fromInt(0),
      Fecha::fromString("2020-01-01"),
      Hora::fromString("14:00"),
    );

    $this->assertTrue($sesion->editable());
  }

  public function testAvailableSesion_Case2() {
    $sesion = Sesion::fromPrimitives(
      Id::fromInt(0),
      Fecha::fromString("2020-01-01"),
      Hora::fromString("13:59"),
    );

    $this->assertFalse($sesion->editable());
  }

  public function testAvailableSesion_Case3() {
    $sesion = Sesion::fromPrimitives(
      Id::fromInt(0),
      Fecha::fromString("2020-01-01"),
      Hora::fromString("14:15"),
    );

    $this->assertTrue($sesion->editable());
  }
}
